name: grpc_test_demo
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  grpc: ^2.1.3
  protobuf: ^1.0.1
  hive: ^1.4.0+1
  rxdart: ^0.23.1
  fixnum: ^0.10.11

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
  hive_generator: ^0.7.0
  build_runner: ^1.7.4
